apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero-app-rolling
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: zero-app
  template:
    metadata:
      labels:
        app: zero-app
    spec:
      containers:
      - name: zero-app
        image: mdea87/k8s-0dt-app:v2
        ports:
        - containerPort: 8080