apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: zero-app-rollout
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: {duration: 20}
        - setWeight: 50
        - pause: {duration: 20}
        - setWeight: 100
  selector:
    matchLabels:
      app: zero-app-rollout
  template:
    metadata:
      labels:
        app: zero-app-rollout
    spec:
      containers:
      - name: zero-app
        image: mdea87/k8s-0dt-app:v2
        ports:
        - containerPort: 8080